name: test

on:
  pull_request:
    paths-ignore:
      - '*.md'

jobs:
  test:
    name: on ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest]
        # os: [ubuntu-latest, windows-latest]
        # machines: [1, 2]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Caching
        uses: actions/cache@master
        with:
          path: |
            ~/.cache
            !~/.cache/exclude
            ~/.static
            !~/.exclude
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}

      - name: Installation
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node }}
        run: npm i

      - name: Run cypress test
        run: npm run test
        env:
          CI: true
          PORT: 5000
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

      - name: Artifact upload screenshots
        uses: actions/upload-artifact@master
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      - name: Size images
        run: npx image-size cypress/screenshots/**/*.png
        working-directory: ./

      - name: Artifact upload chrome screenshots
        uses: actions/upload-artifact@master
        with:
          name: screenshots-chrome
          path: cypress/screenshots/chrome

      - name: Artifact upload videos
        uses: actions/upload-artifact@master
        with:
          name: upload chrome-videos
          path: cypress/videos/chrome

      - run: |
          npx image-size cypress/screenshots/**/*.png
          ffprobe cypress/videos/*.mp4 || true
          mplayer -really-quiet -ao null -vo null -identify -frames 0 cypress/videos/*.mp4 || true
        working-directory: ./
